DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS request CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner       BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description varchar(1024)                           NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_owner_id_it FOREIGN KEY (owner) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS request
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author           BIGINT                                  NOT NULL,
    item_description varchar(1024)                           NOT NULL,
    created          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_user_id_rq FOREIGN KEY (author) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS booking
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booker         BIGINT                                  NOT NULL,
    item           BIGINT                                  NOT NULL,
    start          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    stop           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    confirm_status VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booker_id_bk FOREIGN KEY (booker) REFERENCES users (id),
    CONSTRAINT fk_item_id_bk FOREIGN KEY (item) REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item    BIGINT                                  NOT NULL,
    author  BIGINT                                  NOT NULL,
    comment TEXT                                    NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_author_name_cm FOREIGN KEY (author) REFERENCES users (id),
    CONSTRAINT fk_item_id_cm FOREIGN KEY (item) REFERENCES items (id)
)

